plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    buildFeatures {
        buildConfig true
    }
    namespace 'com.danike.ai'
    compileSdk 35

    defaultConfig {
        def youtubeKeyFile = file(System.getProperty("user.home") + "/.config/danikeai_youtube_key")
        def youtubeKey = youtubeKeyFile.exists() ? youtubeKeyFile.text.trim() : ""
        buildConfigField "String", "YOUTUBE_API_KEY", "\"${youtubeKey}\""
        applicationId 'com.danike.ai'
        minSdk 23
        targetSdk 35
        versionCode 26
        versionName '1.7.9'
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.19.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-storage'
}
